import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ArrowRight, Loader2, Sparkles, CheckCircle2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import SEO from "@/components/SEO";

type FormErrors = { firstName?: string; lastName?: string; email?: string; company?: string; teamSize?: string; meetingTool?: string };

const TEAM_SIZES = ["1–10", "11–50", "51–200", "201–1000", "1000+"];
const MEETING_TOOLS = ["Google Meet", "Zoom", "Microsoft Teams", "Other"];

const selectClass =
  "flex h-10 w-full rounded-md border border-border bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2";

const EarlyAccess = () => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [company, setCompany] = useState("");
  const [teamSize, setTeamSize] = useState("");
  const [meetingTool, setMeetingTool] = useState("");
  const [meetingProblem, setMeetingProblem] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [errors, setErrors] = useState<FormErrors>({});
  const { toast } = useToast();


  const validateEmail = (email: string) => {
    const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return regex.test(email);
  };

  const validateForm = () => {
    const newErrors: FormErrors = {};

    if (!firstName.trim()) {
      newErrors.firstName = "First name is required";
    } else if (firstName.trim().length > 50) {
      newErrors.firstName = "First name must be less than 50 characters";
    }

    if (!lastName.trim()) {
      newErrors.lastName = "Last name is required";
    } else if (lastName.trim().length > 50) {
      newErrors.lastName = "Last name must be less than 50 characters";
    }

    if (!email.trim()) {
      newErrors.email = "Email is required";
    } else if (!validateEmail(email)) {
      newErrors.email = "Please enter a valid email";
    } else if (email.trim().length > 100) {
      newErrors.email = "Email must be less than 100 characters";
    }

    if (!company.trim()) {
      newErrors.company = "Company is required";
    } else if (company.trim().length > 100) {
      newErrors.company = "Company must be less than 100 characters";
    }
    if (!teamSize) newErrors.teamSize = "Pick your team size";
    if (!meetingTool) newErrors.meetingTool = "Pick the tool you meet on most";

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsLoading(true);

    const base = {
      first_name: firstName.trim(),
      last_name: lastName.trim(),
      email: email.trim().toLowerCase(),
    };
    const qualifiers = {
      company: company.trim(),
      team_size: teamSize,
      meeting_tool: meetingTool,
      meeting_problem: meetingProblem.trim().slice(0, 1000) || null,
    };

    // The qualifier columns come from a migration; types.ts (generated by Lovable) may not list them yet
    let { error } = await supabase
      .from("early_access_signups")
      .insert({ ...base, ...qualifiers } as unknown as typeof base);
    // Until the migration adding the qualifier columns is applied, keep signups working without them
    if (error && (error.code === "PGRST204" || /column/i.test(error.message || ""))) {
      ({ error } = await supabase.from("early_access_signups").insert(base));
    }

    if (error) {
      setIsLoading(false);
      if (error.code === "23505") {
        toast({
          title: "Already signed up",
          description: "This email is already on our early access list.",
          variant: "destructive",
        });
      } else {
        toast({
          title: "Something went wrong",
          description: "Please try again later.",
          variant: "destructive",
        });
      }
      return;
    }

    // Welcome email + team notification (edge function, sends with Resend). Never blocks the signup.
    try {
      const { error: emailError } = await supabase.functions.invoke("trigger-webhook", {
        body: { email: base.email },
      });
      if (emailError) console.error("Signup emails failed:", emailError);
    } catch (emailError) {
      console.error("Signup emails failed:", emailError);
    }

    setIsLoading(false);
    setIsSubmitted(true);

    toast({
      title: "Thanks! We got your request.",
      description: "We'll reach out within a few days.",
    });
  };

  const benefits = [
    "Meetings that end in action, and stay that way",
    "Private feedback to run shorter, better meetings",
    "Shape the product with the team building it",
    "Free while in beta",
  ];

  if (isSubmitted) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center px-6">
        <div className="max-w-md w-full text-center">
          <div className="w-20 h-20 bg-accent/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <CheckCircle2 className="w-10 h-10 text-accent" />
          </div>
          <h1 className="text-3xl font-bold text-foreground mb-4">
            Thanks, {firstName}!
          </h1>
          <p className="text-muted-foreground mb-8">
            We got your request. We'll reach out within a few days to learn how your team meets
            and see if you're a fit for the private beta.
          </p>
          <Link to="/">
            <Button variant="hero" size="lg">
              Back to Home
            </Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="Request Early Access — Corteza"
        description="Request a spot in Corteza's private beta: meetings that close the loop, with decisions that stick and commitments that get done."
        path="/early-access"
      />
      {/* Header */}
      <header className="py-6 border-b border-border">
        <div className="container mx-auto px-6">
          <Link to="/" className="text-xl font-bold text-foreground hover:text-accent transition-colors">
            corteza.app
          </Link>
        </div>
      </header>

      <div className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="grid md:grid-cols-2 gap-12 items-start">
            {/* Left side - Info */}
            <div>
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent/10 text-accent mb-6">
                <Sparkles className="w-4 h-4" />
                <span className="text-sm font-medium">Early Access</span>
              </div>

              <h1 className="text-4xl font-bold text-foreground mb-4">
                Request early access
              </h1>

              <p className="text-lg text-muted-foreground mb-8">
                We're opening a private beta for a small number of teams. Tell us a bit about how
                your team meets and we'll reach out to see if it's a fit.
              </p>

              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center gap-3">
                    <CheckCircle2 className="w-5 h-5 text-accent flex-shrink-0" />
                    <span className="text-muted-foreground">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Right side - Form */}
            <div className="bg-card border border-border rounded-2xl p-8 shadow-elegant">
              <h2 className="text-xl font-semibold text-foreground mb-6">
                About you and your team
              </h2>

              <form onSubmit={handleSubmit} className="space-y-5">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="firstName">First name</Label>
                    <Input
                      id="firstName"
                      type="text"
                      placeholder="John"
                      value={firstName}
                      onChange={(e) => {
                        setFirstName(e.target.value);
                        if (errors.firstName) setErrors({ ...errors, firstName: undefined });
                      }}
                      className="bg-background border-border"
                    />
                    {errors.firstName && (
                      <p className="text-destructive text-sm">{errors.firstName}</p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="lastName">Last name</Label>
                    <Input
                      id="lastName"
                      type="text"
                      placeholder="Doe"
                      value={lastName}
                      onChange={(e) => {
                        setLastName(e.target.value);
                        if (errors.lastName) setErrors({ ...errors, lastName: undefined });
                      }}
                      className="bg-background border-border"
                    />
                    {errors.lastName && (
                      <p className="text-destructive text-sm">{errors.lastName}</p>
                    )}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="email">Work email</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="john@company.com"
                    value={email}
                    onChange={(e) => {
                      setEmail(e.target.value);
                      if (errors.email) setErrors({ ...errors, email: undefined });
                    }}
                    className="bg-background border-border"
                  />
                  {errors.email && (
                    <p className="text-destructive text-sm">{errors.email}</p>
                  )}
                </div>

                <div className="space-y-2">
                  <Label htmlFor="company">Company</Label>
                  <Input
                    id="company"
                    type="text"
                    placeholder="Acme Inc."
                    value={company}
                    onChange={(e) => {
                      setCompany(e.target.value);
                      if (errors.company) setErrors({ ...errors, company: undefined });
                    }}
                    className="bg-background border-border"
                  />
                  {errors.company && <p className="text-destructive text-sm">{errors.company}</p>}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="teamSize">Team size</Label>
                    <select
                      id="teamSize"
                      value={teamSize}
                      onChange={(e) => {
                        setTeamSize(e.target.value);
                        if (errors.teamSize) setErrors({ ...errors, teamSize: undefined });
                      }}
                      className={selectClass}
                    >
                      <option value="">Select…</option>
                      {TEAM_SIZES.map((size) => <option key={size} value={size}>{size}</option>)}
                    </select>
                    {errors.teamSize && <p className="text-destructive text-sm">{errors.teamSize}</p>}
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="meetingTool">You meet mostly on</Label>
                    <select
                      id="meetingTool"
                      value={meetingTool}
                      onChange={(e) => {
                        setMeetingTool(e.target.value);
                        if (errors.meetingTool) setErrors({ ...errors, meetingTool: undefined });
                      }}
                      className={selectClass}
                    >
                      <option value="">Select…</option>
                      {MEETING_TOOLS.map((tool) => <option key={tool} value={tool}>{tool}</option>)}
                    </select>
                    {errors.meetingTool && <p className="text-destructive text-sm">{errors.meetingTool}</p>}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="meetingProblem">
                    What's your biggest meeting problem? <span className="text-muted-foreground font-normal">(optional)</span>
                  </Label>
                  <Textarea
                    id="meetingProblem"
                    rows={3}
                    maxLength={1000}
                    placeholder="e.g. We keep re-discussing the same topics and nobody follows up."
                    value={meetingProblem}
                    onChange={(e) => setMeetingProblem(e.target.value)}
                    className="bg-background border-border"
                  />
                </div>

                <Button
                  type="submit"
                  variant="hero"
                  size="lg"
                  className="w-full group"
                  disabled={isLoading}
                >
                  {isLoading ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    <>
                      Request early access
                      <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </>
                  )}
                </Button>

                <p className="text-xs text-muted-foreground text-center">
                  By signing up, you agree to our{" "}
                  <Link to="/terms" className="underline hover:text-foreground">
                    Terms of Service
                  </Link>{" "}
                  and{" "}
                  <Link to="/privacy" className="underline hover:text-foreground">
                    Privacy Policy
                  </Link>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EarlyAccess;
